# vi: set ft=yaml :

# NOTE: The below 2 variables should not need to be changed if you cloned
#   the dotfiles repo to '~/dotfiles'
#  Local home directory
dotfiles_user_home: "{{ '~' | expanduser }}"
# Where your dotfiles live. Probably don't need to change this.
dotfiles_home: "{{dotfiles_user_home}}/dotfiles"

# Name used in commit messages
full_name: Matjah Sonneveld
# Git
# Github username
git_user: raven283
# If you use github, this should be the same as the email
#  used on Github
git_email: matjah@matjah.eu

# GPG Key ID used to sign git commits
# See https://github.com/pstadler/keybase-gpg-github setup instructions
git_signing_key: "{{ lookup('env','GIT_SIGNING_KEY_ID') }}"

# Vim

# Whether to install plugins automatically. If not, just run
# :PlugInstall while in vim.
vim_install_plugins: no

# Utilities that don't get installed by a role
mac_homebrew_packages:
  - curl
  - jq
  - wget
  - highlight
  - terminal-notifier
  - youtube-dl
  - htop-osx
  - httpie
  - postgresql
  - redis
  - diff-so-fancy
  - docker-clean
  - gpg
  # Top for docker containers
  - ctop
  # User-contributed docs for Unix commands
  - tldr
  # what's the wifi password?
  - wifi-password
  # Share tmux sessions
  - tmate
  # README rendering
  - grip
  # For repeating commands
  - watch
  # For displaying a notification when a command finishes
  - noti
  # needed for installing font-cousine
  - svn 

# Mac Apps to be installed with homebrew-cask
mac_cask_packages:
  # Password manager
  - 1password
  # Editor
  - visual-studio-code
  # Browsers
  - google-chrome
  # Utilities
  - appcleaner
  # Docker
  - docker
  # chat
  - slack
  # Video conferencing
  - zoom
  # Notetaking
  - notion
  # Fonts
  - font-ubuntu
  - font-cousine
  - font-hack
  - font-ia-writer-duospace
  # Database client
  - tableplus
  # REST client
  - insomnia
  # Markdown-based presentations
  - deckset

# Mac-App-Store-only apps to be installed with mas
# Use App IDs found with `mas search <name>`
mac_mas_packages:
  # NOTE: the IDs can be found with `mas search <app name>`
  - {"id": 585829637, "name": "Todoist"}

ruby_global_gems:
  - colorls

# Python versions to install with pyenv and set as global
# Especially useful when using tox
pyenv_global_versions:
  - 3.9.0
  - 3.8.6
  - 3.7.4
  - 3.6.8