---
dependencies:
  - geerlingguy.homebrew

galaxy_info:
  role_name: volta
  author: raven283
  description: Volta for macOS
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.5
  platforms:
    - name: MacOSX
      versions:
        - all
        - any
  galaxy_tags:
    - development
    - system
    - volta