- hosts: all

  vars_files:
    - default.config.yaml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yaml"
      tags: ['always']

  roles:
    - common
    - spacevim

  tasks:
    - name: Show Ansible distribution
      debug:
        msg: "You are running {{ ansible_distribution }}"

